/**
 * BYSETPOS Filtering Tests
 *
 * Tests BYSETPOS parameter functionality and array-based optimization.
 * BYSETPOS selects specific occurrences from the set generated by other rules.
 *
 * RFC 5545 Section 3.3.10:
 * "BYSETPOS operates on a SETOF dates, selecting a subset of those dates.
 *  Positive values select from the beginning, negative from the end."
 *
 * Implementation:
 * - Uses array-based filtering for O(1) position access
 * - Supports positive indices (1, 2, 3...) for first, second, third...
 * - Supports negative indices (-1, -2, -3...) for last, second-to-last...
 * - Gracefully handles out-of-range positions (skips)
 *
 * Usage:
 *   psql -d your_database -f tests/test_bysetpos.sql
 */

\set ON_ERROR_STOP on
\set ECHO all

-- Test database setup
-- Ensure we're testing in UTC timezone for consistency
SET timezone = 'UTC';

-- Install RRULE functions (allow override via -v rrule_install=...)
\if :{?rrule_install}
\i :rrule_install
\else
DROP SCHEMA IF EXISTS rrule CASCADE;
CREATE SCHEMA IF NOT EXISTS rrule;
\i src/rrule.sql
\endif

-- Ensure tests do not rely on search_path
SET search_path = public;

BEGIN;

\i tests/helpers.sql

\echo ''
\echo '==================================================================='
\echo 'BYSETPOS Filtering Tests'
\echo '==================================================================='
\echo ''
\echo 'Tests array-based BYSETPOS filtering with positive, negative,'
\echo 'and multiple position indices.'
\echo ''

-- Create test results table
CREATE TEMP TABLE bysetpos_test_results (
    test_category TEXT,
    test_name TEXT,
    status TEXT
);

------------------------------------------------------------------------------------------------------
-- Category 1: Single Position Selection
------------------------------------------------------------------------------------------------------
\echo '==================================================================='
\echo 'Category 1: Single Position Selection'
\echo '==================================================================='

-- Test 1.1: First position (BYSETPOS=1)
-- Use case: First Monday of each month
INSERT INTO bysetpos_test_results (test_category, test_name, status)
VALUES (
    'Single Position',
    'BYSETPOS=1 (first Monday of each month)',
    assert_occurrences_equal(
        'BYSETPOS=1 first Monday',
        ARRAY[
            '2025-01-06 00:00:00'::TIMESTAMP,
            '2025-02-03 00:00:00'::TIMESTAMP,
            '2025-03-03 00:00:00'::TIMESTAMP
        ],
        (SELECT array_agg(occurrence ORDER BY occurrence) FROM rrule."all"('FREQ=MONTHLY;BYDAY=MO;BYSETPOS=1;COUNT=3', '2025-01-01'::TIMESTAMP) AS occurrence)
    )
);

-- Test 1.2: Second position (BYSETPOS=2)
INSERT INTO bysetpos_test_results (test_category, test_name, status)
VALUES (
    'Single Position',
    'BYSETPOS=2 (second Monday of each month)',
    assert_occurrences_equal(
        'BYSETPOS=2 second Monday',
        ARRAY[
            '2025-01-13 00:00:00'::TIMESTAMP,
            '2025-02-10 00:00:00'::TIMESTAMP,
            '2025-03-10 00:00:00'::TIMESTAMP
        ],
        (SELECT array_agg(occurrence ORDER BY occurrence) FROM rrule."all"('FREQ=MONTHLY;BYDAY=MO;BYSETPOS=2;COUNT=3', '2025-01-01'::TIMESTAMP) AS occurrence)
    )
);

-- Test 1.3: Last position (BYSETPOS=-1)
-- Use case: Last Monday of each month
INSERT INTO bysetpos_test_results (test_category, test_name, status)
VALUES (
    'Single Position',
    'BYSETPOS=-1 (last Monday of each month)',
    assert_occurrences_equal(
        'BYSETPOS=-1 last Monday',
        ARRAY[
            '2025-01-27 00:00:00'::TIMESTAMP,
            '2025-02-24 00:00:00'::TIMESTAMP,
            '2025-03-31 00:00:00'::TIMESTAMP
        ],
        (SELECT array_agg(occurrence ORDER BY occurrence) FROM rrule."all"('FREQ=MONTHLY;BYDAY=MO;BYSETPOS=-1;COUNT=3', '2025-01-01'::TIMESTAMP) AS occurrence)
    )
);

-- Test 1.4: Second-to-last position (BYSETPOS=-2)
INSERT INTO bysetpos_test_results (test_category, test_name, status)
VALUES (
    'Single Position',
    'BYSETPOS=-2 (second-to-last Monday)',
    assert_occurrences_equal(
        'BYSETPOS=-2 second-to-last Monday',
        ARRAY[
            '2025-01-20 00:00:00'::TIMESTAMP,
            '2025-02-17 00:00:00'::TIMESTAMP,
            '2025-03-24 00:00:00'::TIMESTAMP
        ],
        (SELECT array_agg(occurrence ORDER BY occurrence) FROM rrule."all"('FREQ=MONTHLY;BYDAY=MO;BYSETPOS=-2;COUNT=3', '2025-01-01'::TIMESTAMP) AS occurrence)
    )
);

------------------------------------------------------------------------------------------------------
-- Category 2: Multiple Position Selection
------------------------------------------------------------------------------------------------------
\echo ''
\echo '==================================================================='
\echo 'Category 2: Multiple Position Selection'
\echo '==================================================================='

-- Test 2.1: First and third (BYSETPOS=1,3)
-- Expected: 1st Mon (Jan 6), 3rd Mon (Jan 20), 1st Mon (Feb 3)
INSERT INTO bysetpos_test_results (test_category, test_name, status)
VALUES (
    'Multiple Positions',
    'BYSETPOS=1,3 (first and third Monday)',
    assert_occurrences_equal(
        'BYSETPOS=1,3 first and third Monday',
        ARRAY[
            '2025-01-06 00:00:00'::TIMESTAMP,
            '2025-01-20 00:00:00'::TIMESTAMP,
            '2025-02-03 00:00:00'::TIMESTAMP
        ],
        (SELECT array_agg(occurrence ORDER BY occurrence) FROM rrule."all"('FREQ=MONTHLY;BYDAY=MO;BYSETPOS=1,3;COUNT=3', '2025-01-01'::TIMESTAMP) AS occurrence)
    )
);

-- Test 2.2: First and last (BYSETPOS=1,-1)
-- Should get 2 per month (first and last Monday), COUNT=4 means 4 total
INSERT INTO bysetpos_test_results (test_category, test_name, status)
VALUES (
    'Multiple Positions',
    'BYSETPOS=1,-1 (first and last Monday)',
    assert_occurrences_equal(
        'BYSETPOS=1,-1 first and last Monday',
        ARRAY[
            '2025-01-06 00:00:00'::TIMESTAMP,
            '2025-01-27 00:00:00'::TIMESTAMP,
            '2025-02-03 00:00:00'::TIMESTAMP,
            '2025-02-24 00:00:00'::TIMESTAMP
        ],
        (SELECT array_agg(occurrence ORDER BY occurrence) FROM rrule."all"('FREQ=MONTHLY;BYDAY=MO;BYSETPOS=1,-1;COUNT=4', '2025-01-01'::TIMESTAMP) AS occurrence)
    )
);

-- Test 2.3: Multiple weekdays with multiple positions
-- Weekly, all weekdays (MO-FR), get only first 2 each week
-- Should get 2 per week (first 2 weekdays), stop at COUNT=3 means 3 total
INSERT INTO bysetpos_test_results (test_category, test_name, status)
VALUES (
    'Multiple Positions',
    'BYSETPOS=1,2 with BYDAY=MO,TU,WE,TH,FR',
    assert_occurrences_equal(
        'BYSETPOS=1,2 with BYDAY=MO,TU,WE,TH,FR',
        ARRAY[
            '2025-01-06 00:00:00'::TIMESTAMP,
            '2025-01-07 00:00:00'::TIMESTAMP,
            '2025-01-13 00:00:00'::TIMESTAMP
        ],
        (SELECT array_agg(occurrence ORDER BY occurrence) FROM rrule."all"('FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR;BYSETPOS=1,2;COUNT=3', '2025-01-06'::TIMESTAMP) AS occurrence)
    )
);

------------------------------------------------------------------------------------------------------
-- Category 3: Edge Cases
------------------------------------------------------------------------------------------------------
\echo ''
\echo '==================================================================='
\echo 'Category 3: Edge Cases'
\echo '==================================================================='

-- Test 3.1: Out of range positive (BYSETPOS=6)
-- January has 4-5 Mondays, asking for 6th should skip
-- Should return 0 because no month has 6 Mondays
INSERT INTO bysetpos_test_results (test_category, test_name, status)
VALUES (
    'Edge Cases',
    'BYSETPOS=6 out of range (should skip gracefully)',
    assert_occurrences_equal(
        'BYSETPOS=6 out of range',
        ARRAY[]::TIMESTAMP[],
        (SELECT array_agg(occurrence ORDER BY occurrence) FROM rrule."all"('FREQ=MONTHLY;BYDAY=MO;BYSETPOS=6;COUNT=5', '2025-01-01'::TIMESTAMP) AS occurrence)
    )
);

-- Test 3.2: Out of range negative (BYSETPOS=-10)
-- Should return 0 because no month has 10 Mondays
INSERT INTO bysetpos_test_results (test_category, test_name, status)
VALUES (
    'Edge Cases',
    'BYSETPOS=-10 out of range negative (should skip)',
    assert_occurrences_equal(
        'BYSETPOS=-10 out of range negative',
        ARRAY[]::TIMESTAMP[],
        (SELECT array_agg(occurrence ORDER BY occurrence) FROM rrule."all"('FREQ=MONTHLY;BYDAY=MO;BYSETPOS=-10;COUNT=5', '2025-01-01'::TIMESTAMP) AS occurrence)
    )
);

-- Test 3.3: BYSETPOS with COUNT=1 (minimum) - exact date assertion
-- First Monday of January 2025 = Jan 6
INSERT INTO bysetpos_test_results (test_category, test_name, status)
VALUES (
    'Edge Cases',
    'BYSETPOS=1 with COUNT=1 (minimum)',
    assert_occurrences_equal(
        'BYSETPOS=1 COUNT=1',
        ARRAY['2025-01-06 00:00:00'::TIMESTAMP],
        (SELECT array_agg(occurrence ORDER BY occurrence) FROM rrule."all"('FREQ=MONTHLY;BYDAY=MO;BYSETPOS=1;COUNT=1', '2025-01-01'::TIMESTAMP) AS occurrence)
    )
);

-- Test 3.4: Mixed positive and negative with gaps (BYSETPOS=1,3,-2,-1)
-- Jan 2025 Mondays: 6,13,20,27 → pos 1=6, pos 3=20, pos -2=20, pos -1=27
-- After dedup: 6, 20, 27 from Jan; then Feb Mondays: 3,10,17,24 → 3, 17, 17, 24 → 3, 17, 24
-- COUNT=8 picks first 8 distinct from rolling months
INSERT INTO bysetpos_test_results (test_category, test_name, status)
VALUES (
    'Edge Cases',
    'BYSETPOS=1,3,-2,-1 (complex mixed)',
    assert_occurrences_equal(
        'BYSETPOS=1,3,-2,-1 mixed complex',
        ARRAY[
            '2025-01-06 00:00:00'::TIMESTAMP,
            '2025-01-20 00:00:00'::TIMESTAMP,
            '2025-01-27 00:00:00'::TIMESTAMP,
            '2025-02-03 00:00:00'::TIMESTAMP,
            '2025-02-17 00:00:00'::TIMESTAMP,
            '2025-02-24 00:00:00'::TIMESTAMP,
            '2025-03-03 00:00:00'::TIMESTAMP,
            '2025-03-17 00:00:00'::TIMESTAMP
        ],
        (SELECT array_agg(occurrence ORDER BY occurrence) FROM rrule."all"('FREQ=MONTHLY;BYDAY=MO;BYSETPOS=1,3,-2,-1;COUNT=8', '2025-01-01'::TIMESTAMP) AS occurrence)
    )
);

-- Test 3.5: BYSETPOS with BYMONTHDAY expansion
-- BYMONTHDAY=1,15,28 produces 3 candidates per month; BYSETPOS=1,-1 selects first and last
INSERT INTO bysetpos_test_results (test_category, test_name, status)
VALUES (
    'Edge Cases',
    'BYSETPOS=1,-1 with BYMONTHDAY=1,15,28',
    assert_occurrences_equal(
        'BYSETPOS with BYMONTHDAY expansion',
        ARRAY[
            '2025-01-01 00:00:00'::TIMESTAMP,
            '2025-01-28 00:00:00'::TIMESTAMP,
            '2025-02-01 00:00:00'::TIMESTAMP,
            '2025-02-28 00:00:00'::TIMESTAMP
        ],
        (SELECT array_agg(occurrence ORDER BY occurrence) FROM rrule."all"('FREQ=MONTHLY;BYMONTHDAY=1,15,28;BYSETPOS=1,-1;COUNT=4', '2025-01-01'::TIMESTAMP) AS occurrence)
    )
);

------------------------------------------------------------------------------------------------------
-- Category 4: YEARLY + BYSETPOS Tests
------------------------------------------------------------------------------------------------------
\echo ''
\echo '==================================================================='
\echo 'Category 4: YEARLY + BYSETPOS'
\echo '==================================================================='

-- Test 4.1: First Monday of each year (BYSETPOS=1)
-- 2025: Jan 6, 2026: Jan 5, 2027: Jan 4
INSERT INTO bysetpos_test_results (test_category, test_name, status)
VALUES (
    'YEARLY BYSETPOS',
    'BYSETPOS=1 (first Monday of year)',
    assert_occurrences_equal(
        'First Monday of year',
        ARRAY[
            '2025-01-06 00:00:00'::TIMESTAMP,
            '2026-01-05 00:00:00'::TIMESTAMP,
            '2027-01-04 00:00:00'::TIMESTAMP
        ],
        (SELECT array_agg(occurrence ORDER BY occurrence) FROM rrule."all"('FREQ=YEARLY;BYDAY=MO;BYSETPOS=1;COUNT=3', '2025-01-01'::TIMESTAMP) AS occurrence)
    )
);

-- Test 4.2: Last Monday of each year (BYSETPOS=-1)
-- 2025: Dec 29, 2026: Dec 28, 2027: Dec 27
INSERT INTO bysetpos_test_results (test_category, test_name, status)
VALUES (
    'YEARLY BYSETPOS',
    'BYSETPOS=-1 (last Monday of year)',
    assert_occurrences_equal(
        'Last Monday of year',
        ARRAY[
            '2025-12-29 00:00:00'::TIMESTAMP,
            '2026-12-28 00:00:00'::TIMESTAMP,
            '2027-12-27 00:00:00'::TIMESTAMP
        ],
        (SELECT array_agg(occurrence ORDER BY occurrence) FROM rrule."all"('FREQ=YEARLY;BYDAY=MO;BYSETPOS=-1;COUNT=3', '2025-01-01'::TIMESTAMP) AS occurrence)
    )
);

------------------------------------------------------------------------------------------------------
-- Category 5: Coverage Gap Tests
------------------------------------------------------------------------------------------------------
\echo ''
\echo '==================================================================='
\echo 'Category 5: Coverage Gap Tests'
\echo '==================================================================='

-- Test 5.1: BYSETPOS + WEEKLY + INTERVAL>1
-- Verifies BYSETPOS selects first and last from each bi-weekly candidate set.
-- BYDAY=MO,WE,FR produces 3 candidates per active week; INTERVAL=2 skips alternate weeks.
-- Week of Jan 6 (active): MO=6, WE=8, FR=10 → BYSETPOS 1=6, -1=10
-- Week of Jan 13 (skipped by INTERVAL=2)
-- Week of Jan 20 (active): MO=20, WE=22, FR=24 → BYSETPOS 1=20, -1=24
-- Week of Feb 3 (active): MO=3, WE=5, FR=7 → BYSETPOS 1=Feb 3, -1=Feb 7
INSERT INTO bysetpos_test_results (test_category, test_name, status)
VALUES (
    'Coverage Gaps',
    'BYSETPOS=1,-1 with WEEKLY INTERVAL=2 BYDAY=MO,WE,FR',
    assert_occurrences_equal(
        'BYSETPOS + WEEKLY + INTERVAL>1',
        ARRAY[
            '2025-01-06 10:00:00'::TIMESTAMP,
            '2025-01-10 10:00:00'::TIMESTAMP,
            '2025-01-20 10:00:00'::TIMESTAMP,
            '2025-01-24 10:00:00'::TIMESTAMP,
            '2025-02-03 10:00:00'::TIMESTAMP,
            '2025-02-07 10:00:00'::TIMESTAMP
        ],
        (SELECT array_agg(occurrence ORDER BY occurrence) FROM rrule."all"('FREQ=WEEKLY;INTERVAL=2;BYDAY=MO,WE,FR;BYSETPOS=1,-1;COUNT=6', '2025-01-06 10:00:00'::TIMESTAMP) AS occurrence)
    )
);

-- Test 5.2: BYSETPOS + BYWEEKNO on YEARLY
-- Verifies BYSETPOS operates correctly when combined with BYWEEKNO.
-- BYWEEKNO=20 with BYDAY=MO,WE,FR produces 3 candidates in ISO week 20.
-- BYSETPOS=1,-1 selects the first (Monday) and last (Friday) from that set.
-- 2025 ISO wk 20: Mon May 12, Fri May 16
-- 2026 ISO wk 20: Mon May 11, Fri May 15
-- 2027 ISO wk 20: Mon May 17, Fri May 21
INSERT INTO bysetpos_test_results (test_category, test_name, status)
VALUES (
    'Coverage Gaps',
    'BYSETPOS=1,-1 with YEARLY BYWEEKNO=20 BYDAY=MO,WE,FR',
    assert_occurrences_equal(
        'BYSETPOS + BYWEEKNO on YEARLY',
        ARRAY[
            '2025-05-12 09:00:00'::TIMESTAMP,
            '2025-05-16 09:00:00'::TIMESTAMP,
            '2026-05-11 09:00:00'::TIMESTAMP,
            '2026-05-15 09:00:00'::TIMESTAMP,
            '2027-05-17 09:00:00'::TIMESTAMP,
            '2027-05-21 09:00:00'::TIMESTAMP
        ],
        (SELECT array_agg(occurrence ORDER BY occurrence) FROM rrule."all"('FREQ=YEARLY;BYWEEKNO=20;BYDAY=MO,WE,FR;BYSETPOS=1,-1;COUNT=6', '2025-01-01 09:00:00'::TIMESTAMP) AS occurrence)
    )
);

-- Test 5.3: BYSETPOS + DAILY frequency with BYDAY filter
-- DAILY with BYDAY=MO,WE,FR produces one candidate per qualifying day.
-- BYSETPOS=1 on a single-element daily set passes through unchanged.
-- Expected: same results as without BYSETPOS — Jan 6 (Mon), Jan 8 (Wed), Jan 10 (Fri).
INSERT INTO bysetpos_test_results (test_category, test_name, status)
VALUES (
    'Coverage Gaps',
    'BYSETPOS=1 with DAILY BYDAY=MO,WE,FR (single-element set passthrough)',
    assert_occurrences_equal(
        'BYSETPOS + DAILY with BYDAY',
        ARRAY[
            '2025-01-06 10:00:00'::TIMESTAMP,
            '2025-01-08 10:00:00'::TIMESTAMP,
            '2025-01-10 10:00:00'::TIMESTAMP
        ],
        (SELECT array_agg(occurrence ORDER BY occurrence) FROM rrule."all"('FREQ=DAILY;BYDAY=MO,WE,FR;BYSETPOS=1;COUNT=3', '2025-01-06 10:00:00'::TIMESTAMP) AS occurrence)
    )
);

------------------------------------------------------------------------------------------------------
-- Category 6: YEARLY + BYMONTH + BYDAY + BYSETPOS
------------------------------------------------------------------------------------------------------
\echo ''
\echo '==================================================================='
\echo 'Category 6: YEARLY + BYMONTH + BYDAY + BYSETPOS'
\echo '==================================================================='

-- Test 6.1: First and last weekday of January each year
-- FREQ=YEARLY;BYMONTH=1 restricts to January; BYDAY=MO,TU,WE,TH,FR expands to all weekdays;
-- BYSETPOS=1,-1 selects first and last weekday from the January set.
-- 2025 Jan: first weekday = Wed Jan 1, last weekday = Fri Jan 31
-- 2026 Jan: first weekday = Thu Jan 1, last weekday = Fri Jan 30
-- 2027 Jan: first weekday = Fri Jan 1, last weekday = Fri Jan 29
INSERT INTO bysetpos_test_results (test_category, test_name, status)
VALUES (
    'YEARLY+BYMONTH+BYDAY+BYSETPOS',
    'BYSETPOS=1,-1 first and last weekday of January',
    assert_occurrences_equal(
        'First and last weekday of January each year',
        ARRAY[
            '2025-01-01 00:00:00'::TIMESTAMP,
            '2025-01-31 00:00:00'::TIMESTAMP,
            '2026-01-01 00:00:00'::TIMESTAMP,
            '2026-01-30 00:00:00'::TIMESTAMP,
            '2027-01-01 00:00:00'::TIMESTAMP,
            '2027-01-29 00:00:00'::TIMESTAMP
        ],
        (SELECT array_agg(occurrence ORDER BY occurrence) FROM rrule."all"('FREQ=YEARLY;BYMONTH=1;BYDAY=MO,TU,WE,TH,FR;BYSETPOS=1,-1;COUNT=6', '2025-01-01 00:00:00'::TIMESTAMP) AS occurrence)
    )
);

------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------
-- Category 7: BYSETPOS + SKIP Interaction Tests
------------------------------------------------------------------------------------------------------
\echo ''
\echo '==================================================================='
\echo 'Category 7: BYSETPOS + SKIP Interaction Tests'
\echo '==================================================================='

-- Test 7.1: SKIP=FORWARD deduplication before BYSETPOS
-- BYMONTHDAY=30,31 in February: both 30 and 31 are invalid, SKIP=FORWARD moves both to Mar 1.
-- After deduplication, Feb produces only 1 candidate (Mar 1), so BYSETPOS=1 and -1 both select it.
-- Jan: 30,31 → BYSETPOS=1,-1 → Jan 30, Jan 31 (2 results)
-- Feb: both forward to Mar 1 → deduped to 1 candidate → BYSETPOS=1,-1 both select Mar 1 (1 result)
-- Mar: 30,31 → BYSETPOS=1,-1 → Mar 30, Mar 31 (2 results)
-- Apr: 30 exists, 31 forwards to May 1 → BYSETPOS=1,-1 → Apr 30, May 1 (need 1 more for COUNT=6)
-- COUNT=6 stops after 6 total
INSERT INTO bysetpos_test_results (test_category, test_name, status)
VALUES (
    'BYSETPOS+SKIP',
    'SKIP=FORWARD dedup before BYSETPOS (BYMONTHDAY=30,31;BYSETPOS=1,-1)',
    assert_occurrences_equal(
        'SKIP=FORWARD dedup before BYSETPOS',
        ARRAY[
            '2025-01-30 10:00:00'::TIMESTAMP,
            '2025-01-31 10:00:00'::TIMESTAMP,
            '2025-03-01 10:00:00'::TIMESTAMP,
            '2025-03-30 10:00:00'::TIMESTAMP,
            '2025-03-31 10:00:00'::TIMESTAMP,
            '2025-04-30 10:00:00'::TIMESTAMP
        ],
        (SELECT array_agg(occurrence ORDER BY occurrence) FROM rrule."all"(
            'FREQ=MONTHLY;BYMONTHDAY=30,31;SKIP=FORWARD;RSCALE=GREGORIAN;BYSETPOS=1,-1;COUNT=6',
            '2025-01-01 10:00:00'::TIMESTAMP
        ) AS occurrence)
    )
);

-- Test 7.2: SKIP=BACKWARD deduplication before BYSETPOS
-- BYMONTHDAY=30,31 in February: both invalid, SKIP=BACKWARD moves both to Feb 28.
-- After deduplication, Feb produces 1 candidate (Feb 28).
-- Jan: 30,31 → Jan 30, Jan 31
-- Feb: both backward to Feb 28 → 1 candidate → Feb 28
-- Mar: 30,31 → Mar 30, Mar 31
-- Apr: 30 exists, 31 backward to Apr 30 → deduped to 1 candidate → Apr 30
-- COUNT=6 stops after 6 total
INSERT INTO bysetpos_test_results (test_category, test_name, status)
VALUES (
    'BYSETPOS+SKIP',
    'SKIP=BACKWARD dedup before BYSETPOS (BYMONTHDAY=30,31;BYSETPOS=1,-1)',
    assert_occurrences_equal(
        'SKIP=BACKWARD dedup before BYSETPOS',
        ARRAY[
            '2025-01-30 10:00:00'::TIMESTAMP,
            '2025-01-31 10:00:00'::TIMESTAMP,
            '2025-02-28 10:00:00'::TIMESTAMP,
            '2025-03-30 10:00:00'::TIMESTAMP,
            '2025-03-31 10:00:00'::TIMESTAMP,
            '2025-04-30 10:00:00'::TIMESTAMP
        ],
        (SELECT array_agg(occurrence ORDER BY occurrence) FROM rrule."all"(
            'FREQ=MONTHLY;BYMONTHDAY=30,31;SKIP=BACKWARD;RSCALE=GREGORIAN;BYSETPOS=1,-1;COUNT=6',
            '2025-01-01 10:00:00'::TIMESTAMP
        ) AS occurrence)
    )
);

-- Test 7.3: YEARLY SKIP=FORWARD + BYSETPOS on leap day
-- BYMONTHDAY=29 in February: invalid in non-leap years, SKIP=FORWARD moves to Mar 1.
-- BYSETPOS=1 selects the single candidate each year.
-- 2024 (leap): Feb 29 exists → selected
-- 2025-2027 (non-leap): Feb 29 → forwarded to Mar 1 → selected
INSERT INTO bysetpos_test_results (test_category, test_name, status)
VALUES (
    'BYSETPOS+SKIP',
    'YEARLY SKIP=FORWARD leap day + BYSETPOS=1',
    assert_occurrences_equal(
        'YEARLY SKIP=FORWARD leap day BYSETPOS',
        ARRAY[
            '2024-02-29 10:00:00'::TIMESTAMP,
            '2025-03-01 10:00:00'::TIMESTAMP,
            '2026-03-01 10:00:00'::TIMESTAMP,
            '2027-03-01 10:00:00'::TIMESTAMP
        ],
        (SELECT array_agg(occurrence ORDER BY occurrence) FROM rrule."all"(
            'FREQ=YEARLY;BYMONTH=2;BYMONTHDAY=29;SKIP=FORWARD;RSCALE=GREGORIAN;BYSETPOS=1;COUNT=4',
            '2024-01-01 10:00:00'::TIMESTAMP
        ) AS occurrence)
    )
);

-- Test 7.4: YEARLY SKIP=BACKWARD + BYSETPOS on leap day
-- BYMONTHDAY=29 in February: invalid in non-leap years, SKIP=BACKWARD moves to Feb 28.
-- 2024 (leap): Feb 29 exists → selected
-- 2025-2027 (non-leap): Feb 29 → backward to Feb 28 → selected
INSERT INTO bysetpos_test_results (test_category, test_name, status)
VALUES (
    'BYSETPOS+SKIP',
    'YEARLY SKIP=BACKWARD leap day + BYSETPOS=1',
    assert_occurrences_equal(
        'YEARLY SKIP=BACKWARD leap day BYSETPOS',
        ARRAY[
            '2024-02-29 10:00:00'::TIMESTAMP,
            '2025-02-28 10:00:00'::TIMESTAMP,
            '2026-02-28 10:00:00'::TIMESTAMP,
            '2027-02-28 10:00:00'::TIMESTAMP
        ],
        (SELECT array_agg(occurrence ORDER BY occurrence) FROM rrule."all"(
            'FREQ=YEARLY;BYMONTH=2;BYMONTHDAY=29;SKIP=BACKWARD;RSCALE=GREGORIAN;BYSETPOS=1;COUNT=4',
            '2024-01-01 10:00:00'::TIMESTAMP
        ) AS occurrence)
    )
);

-- Test 7.5: SKIP=FORWARD + BYSETPOS with INTERVAL > 1
-- INTERVAL=2 skips every other month. Starting Jan 2025: Jan, Mar, May, Jul, Sep, Nov.
-- All odd months have 31 days, so BYMONTHDAY=30,31 are both valid — no SKIP forwarding needed.
-- BYSETPOS=1,-1 selects first (30) and last (31) from each active month.
-- COUNT=6 → Jan 30, Jan 31, Mar 30, Mar 31, May 30, May 31
INSERT INTO bysetpos_test_results (test_category, test_name, status)
VALUES (
    'BYSETPOS+SKIP',
    'SKIP=FORWARD + BYSETPOS + INTERVAL=2',
    assert_occurrences_equal(
        'SKIP=FORWARD BYSETPOS INTERVAL=2',
        ARRAY[
            '2025-01-30 10:00:00'::TIMESTAMP,
            '2025-01-31 10:00:00'::TIMESTAMP,
            '2025-03-30 10:00:00'::TIMESTAMP,
            '2025-03-31 10:00:00'::TIMESTAMP,
            '2025-05-30 10:00:00'::TIMESTAMP,
            '2025-05-31 10:00:00'::TIMESTAMP
        ],
        (SELECT array_agg(occurrence ORDER BY occurrence) FROM rrule."all"(
            'FREQ=MONTHLY;INTERVAL=2;BYMONTHDAY=30,31;SKIP=FORWARD;RSCALE=GREGORIAN;BYSETPOS=1,-1;COUNT=6',
            '2025-01-01 10:00:00'::TIMESTAMP
        ) AS occurrence)
    )
);

-- Test 7.6: SKIP=BACKWARD + BYSETPOS with INTERVAL=3 (hits Feb)
-- INTERVAL=3 starting Feb 2025: Feb, May, Aug, Nov, Feb 2026...
-- Feb 2025: BYMONTHDAY=30,31 both invalid → BACKWARD to Feb 28 (deduped: 1 candidate)
--   BYSETPOS=1,-1 both select Feb 28 → 1 result
-- May 2025: 30,31 both valid → BYSETPOS=1,-1 → May 30, May 31
-- Aug 2025: 30,31 both valid → BYSETPOS=1,-1 → Aug 30, Aug 31
-- COUNT=5 stops at 5 total
INSERT INTO bysetpos_test_results (test_category, test_name, status)
VALUES (
    'BYSETPOS+SKIP',
    'SKIP=BACKWARD + BYSETPOS + INTERVAL=3 (hits Feb)',
    assert_occurrences_equal(
        'SKIP=BACKWARD BYSETPOS INTERVAL=3 hits Feb',
        ARRAY[
            '2025-02-28 10:00:00'::TIMESTAMP,
            '2025-05-30 10:00:00'::TIMESTAMP,
            '2025-05-31 10:00:00'::TIMESTAMP,
            '2025-08-30 10:00:00'::TIMESTAMP,
            '2025-08-31 10:00:00'::TIMESTAMP
        ],
        (SELECT array_agg(occurrence ORDER BY occurrence) FROM rrule."all"(
            'FREQ=MONTHLY;INTERVAL=3;BYMONTHDAY=30,31;SKIP=BACKWARD;RSCALE=GREGORIAN;BYSETPOS=1,-1;COUNT=5',
            '2025-02-01 10:00:00'::TIMESTAMP
        ) AS occurrence)
    )
);

-- Print Test Results
------------------------------------------------------------------------------------------------------
\echo ''
\echo '==================================================================='
\echo 'Test Results'
\echo '==================================================================='
\echo ''

SELECT
    test_category,
    test_name,
    CASE
        WHEN status LIKE 'PASS%' THEN '[PASS] ' || test_name
        ELSE '[FAIL] ' || test_name || ' - ' || status
    END AS result
FROM bysetpos_test_results
ORDER BY test_category, test_name;

-- Check if all tests passed
DO $$
DECLARE
    failed_count INT;
    total_count INT;
BEGIN
    SELECT COUNT(*) INTO failed_count
    FROM bysetpos_test_results
    WHERE status NOT LIKE 'PASS%';

    SELECT COUNT(*) INTO total_count
    FROM bysetpos_test_results;

    RAISE NOTICE '';
    RAISE NOTICE '===================================================================';
    IF failed_count = 0 THEN
        RAISE NOTICE 'BYSETPOS Filtering Tests: % / % PASSED', total_count, total_count;
        RAISE NOTICE '===================================================================';
    ELSE
        RAISE NOTICE 'BYSETPOS Filtering Tests: % / % FAILED', failed_count, total_count;
        RAISE NOTICE '===================================================================';
        RAISE EXCEPTION 'BYSETPOS filtering tests failed';
    END IF;
END $$;

ROLLBACK;
