/**
 * AUTO-GENERATED TEST FILE
 *
 * Generated by: scripts/generate-matrix-tests.js
 * Generated at: 2026-02-03T11:24:29.532Z
 *
 * DO NOT EDIT MANUALLY - regenerate with:
 *   node scripts/generate-matrix-tests.js > tests/matrix/test_generated_matrix.sql
 *
 * This file contains systematic tests for every cell in SPEC_COMPLIANCE.md.
 * Tests are grouped by feature and frequency.
 */

\set ON_ERROR_STOP on
\set ECHO all

SET timezone = 'UTC';

\if :{?rrule_install}
\i :rrule_install
\else
DROP SCHEMA IF EXISTS rrule CASCADE;
CREATE SCHEMA IF NOT EXISTS rrule;
\i src/rrule.sql
\endif

SET search_path = public;

BEGIN;

\i tests/helpers.sql

-- Detect if subday is installed
CREATE TEMP TABLE test_config AS
SELECT EXISTS (
    SELECT 1 FROM pg_proc WHERE proname = 'hourly_set'
    AND pronamespace = (SELECT oid FROM pg_namespace WHERE nspname = 'rrule')
) AS subday_installed;

\echo ''
\echo '====================================================================='
\echo 'AUTO-GENERATED SPEC COMPLIANCE MATRIX TESTS'
\echo '====================================================================='
\echo ''

--------------------------------------------------------------------------------
-- FEATURE: COUNT
--------------------------------------------------------------------------------
\echo ''
\echo '--- COUNT ---'
\echo ''

-- DAILY with COUNT=5
SELECT assert_equals('matrix-daily-count', '5',
    (SELECT COUNT(*)::TEXT FROM rrule."all"('FREQ=DAILY;COUNT=5', '2025-01-01 10:00:00'::TIMESTAMP)));

-- WEEKLY with COUNT=5
SELECT assert_equals('matrix-weekly-count', '5',
    (SELECT COUNT(*)::TEXT FROM rrule."all"('FREQ=WEEKLY;COUNT=5', '2025-01-01 10:00:00'::TIMESTAMP)));

-- MONTHLY with COUNT=5
SELECT assert_equals('matrix-monthly-count', '5',
    (SELECT COUNT(*)::TEXT FROM rrule."all"('FREQ=MONTHLY;COUNT=5', '2025-01-01 10:00:00'::TIMESTAMP)));

-- YEARLY with COUNT=5
SELECT assert_equals('matrix-yearly-count', '5',
    (SELECT COUNT(*)::TEXT FROM rrule."all"('FREQ=YEARLY;COUNT=5', '2025-01-01 10:00:00'::TIMESTAMP)));

-- HOURLY with COUNT=5 (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=HOURLY;COUNT=5', '2025-01-01 10:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-hourly-count]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-hourly-count]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-hourly-count]: Subday not installed';
    END IF;
END $$;

-- MINUTELY with COUNT=5 (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=MINUTELY;COUNT=5', '2025-01-01 10:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-minutely-count]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-minutely-count]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-minutely-count]: Subday not installed';
    END IF;
END $$;

-- SECONDLY with COUNT=5 (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=SECONDLY;COUNT=5', '2025-01-01 10:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-secondly-count]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-secondly-count]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-secondly-count]: Subday not installed';
    END IF;
END $$;

--------------------------------------------------------------------------------
-- FEATURE: UNTIL
--------------------------------------------------------------------------------
\echo ''
\echo '--- UNTIL ---'
\echo ''

-- DAILY with UNTIL
SELECT assert_true('matrix-daily-until',
    (SELECT COUNT(*) >= 1 FROM rrule."all"('FREQ=DAILY;UNTIL=20250131T235959Z', '2025-01-01 10:00:00'::TIMESTAMP)));

-- WEEKLY with UNTIL
SELECT assert_true('matrix-weekly-until',
    (SELECT COUNT(*) >= 1 FROM rrule."all"('FREQ=WEEKLY;UNTIL=20250131T235959Z', '2025-01-01 10:00:00'::TIMESTAMP)));

-- MONTHLY with UNTIL
SELECT assert_true('matrix-monthly-until',
    (SELECT COUNT(*) >= 1 FROM rrule."all"('FREQ=MONTHLY;UNTIL=20250131T235959Z', '2025-01-01 10:00:00'::TIMESTAMP)));

-- YEARLY with UNTIL
SELECT assert_true('matrix-yearly-until',
    (SELECT COUNT(*) >= 1 FROM rrule."all"('FREQ=YEARLY;UNTIL=20250131T235959Z', '2025-01-01 10:00:00'::TIMESTAMP)));

-- HOURLY with UNTIL (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=HOURLY;UNTIL=20250131T235959Z', '2025-01-01 10:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-hourly-until]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-hourly-until]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-hourly-until]: Subday not installed';
    END IF;
END $$;

-- MINUTELY with UNTIL (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=MINUTELY;UNTIL=20250131T235959Z', '2025-01-01 10:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-minutely-until]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-minutely-until]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-minutely-until]: Subday not installed';
    END IF;
END $$;

-- SECONDLY with UNTIL (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=SECONDLY;UNTIL=20250131T235959Z', '2025-01-01 10:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-secondly-until]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-secondly-until]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-secondly-until]: Subday not installed';
    END IF;
END $$;

--------------------------------------------------------------------------------
-- FEATURE: INTERVAL
--------------------------------------------------------------------------------
\echo ''
\echo '--- INTERVAL ---'
\echo ''

-- DAILY with INTERVAL=2
SELECT assert_equals('matrix-daily-interval', '5',
    (SELECT COUNT(*)::TEXT FROM rrule."all"('FREQ=DAILY;INTERVAL=2;COUNT=5', '2025-01-01 10:00:00'::TIMESTAMP)));

-- WEEKLY with INTERVAL=2
SELECT assert_equals('matrix-weekly-interval', '5',
    (SELECT COUNT(*)::TEXT FROM rrule."all"('FREQ=WEEKLY;INTERVAL=2;COUNT=5', '2025-01-01 10:00:00'::TIMESTAMP)));

-- MONTHLY with INTERVAL=2
SELECT assert_equals('matrix-monthly-interval', '5',
    (SELECT COUNT(*)::TEXT FROM rrule."all"('FREQ=MONTHLY;INTERVAL=2;COUNT=5', '2025-01-01 10:00:00'::TIMESTAMP)));

-- YEARLY with INTERVAL=2
SELECT assert_equals('matrix-yearly-interval', '5',
    (SELECT COUNT(*)::TEXT FROM rrule."all"('FREQ=YEARLY;INTERVAL=2;COUNT=5', '2025-01-01 10:00:00'::TIMESTAMP)));

-- HOURLY with INTERVAL=2 (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=HOURLY;INTERVAL=2;COUNT=5', '2025-01-01 10:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-hourly-interval]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-hourly-interval]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-hourly-interval]: Subday not installed';
    END IF;
END $$;

-- MINUTELY with INTERVAL=2 (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=MINUTELY;INTERVAL=2;COUNT=5', '2025-01-01 10:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-minutely-interval]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-minutely-interval]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-minutely-interval]: Subday not installed';
    END IF;
END $$;

-- SECONDLY with INTERVAL=2 (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=SECONDLY;INTERVAL=2;COUNT=5', '2025-01-01 10:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-secondly-interval]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-secondly-interval]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-secondly-interval]: Subday not installed';
    END IF;
END $$;

--------------------------------------------------------------------------------
-- FEATURE: BYDAY
--------------------------------------------------------------------------------
\echo ''
\echo '--- BYDAY ---'
\echo ''

-- DAILY with BYDAY
SELECT assert_true('matrix-daily-byday',
    (SELECT COUNT(*) >= 1 FROM rrule."all"('FREQ=DAILY;BYDAY=MO,WE,FR;COUNT=10', '2025-01-01 10:00:00'::TIMESTAMP)));

-- WEEKLY with BYDAY
SELECT assert_true('matrix-weekly-byday',
    (SELECT COUNT(*) >= 1 FROM rrule."all"('FREQ=WEEKLY;BYDAY=MO,WE,FR;COUNT=10', '2025-01-01 10:00:00'::TIMESTAMP)));

-- MONTHLY with BYDAY
SELECT assert_true('matrix-monthly-byday',
    (SELECT COUNT(*) >= 1 FROM rrule."all"('FREQ=MONTHLY;BYDAY=MO,WE,FR;COUNT=10', '2025-01-01 10:00:00'::TIMESTAMP)));

-- YEARLY with BYDAY
SELECT assert_true('matrix-yearly-byday',
    (SELECT COUNT(*) >= 1 FROM rrule."all"('FREQ=YEARLY;BYMONTH=1;BYDAY=MO;COUNT=5', '2025-01-01 10:00:00'::TIMESTAMP)));

-- HOURLY with BYDAY (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=HOURLY;BYDAY=MO,WE,FR;COUNT=10', '2025-01-01 10:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-hourly-byday]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-hourly-byday]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-hourly-byday]: Subday not installed';
    END IF;
END $$;

-- MINUTELY with BYDAY (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=MINUTELY;BYDAY=MO,WE,FR;COUNT=10', '2025-01-01 10:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-minutely-byday]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-minutely-byday]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-minutely-byday]: Subday not installed';
    END IF;
END $$;

-- SECONDLY with BYDAY (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=SECONDLY;BYDAY=MO,WE,FR;COUNT=10', '2025-01-01 10:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-secondly-byday]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-secondly-byday]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-secondly-byday]: Subday not installed';
    END IF;
END $$;

--------------------------------------------------------------------------------
-- FEATURE: BYDAY_ordinal
--------------------------------------------------------------------------------
\echo ''
\echo '--- BYDAY_ordinal ---'
\echo ''

-- DAILY with BYDAY_ordinal should be rejected
SELECT assert_rrule_rejected('reject-daily-byday-ordinal',
    'FREQ=DAILY;BYDAY=2TU;COUNT=5',
    '%BYDAY with ordinal%can only be used with FREQ=MONTHLY or FREQ=YEARLY%');

-- WEEKLY with BYDAY_ordinal should be rejected
SELECT assert_rrule_rejected('reject-weekly-byday-ordinal',
    'FREQ=WEEKLY;BYDAY=2TU;COUNT=5',
    '%BYDAY with ordinal%can only be used with FREQ=MONTHLY or FREQ=YEARLY%');

-- MONTHLY with BYDAY ordinal (2MO/2TU)
SELECT assert_true('matrix-monthly-byday-ordinal',
    (SELECT COUNT(*) >= 1 FROM rrule."all"('FREQ=MONTHLY;BYDAY=2TU;COUNT=5', '2025-01-01 10:00:00'::TIMESTAMP)));

-- YEARLY with BYDAY ordinal (2MO/2TU)
SELECT assert_true('matrix-yearly-byday-ordinal',
    (SELECT COUNT(*) >= 1 FROM rrule."all"('FREQ=YEARLY;BYMONTH=1;BYDAY=2MO;COUNT=5', '2025-01-01 10:00:00'::TIMESTAMP)));

-- HOURLY with BYDAY_ordinal should be rejected
DO $$
DECLARE
    result TIMESTAMP[];
    err_msg TEXT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        BEGIN
            result := (SELECT array_agg(occurrence ORDER BY occurrence)
                       FROM rrule."all"('FREQ=HOURLY;BYDAY=2TU;COUNT=5', '2025-01-01 10:00:00'::TIMESTAMP) AS occurrence);
            RAISE EXCEPTION 'FAIL [reject-hourly-byday-ordinal]: RRULE was accepted when it should have been rejected';
        EXCEPTION
            WHEN raise_exception THEN
                err_msg := SQLERRM;
                IF err_msg LIKE '%BYDAY with ordinal%can only be used with FREQ=MONTHLY or FREQ=YEARLY%' THEN
                    RAISE NOTICE 'PASS [reject-hourly-byday-ordinal]';
                ELSE
                    RAISE EXCEPTION 'FAIL [reject-hourly-byday-ordinal]: Wrong error. Got: %', err_msg;
                END IF;
        END;
    ELSE
        RAISE NOTICE 'SKIP [reject-hourly-byday-ordinal]: Subday not installed';
    END IF;
END $$;

-- MINUTELY with BYDAY_ordinal should be rejected
DO $$
DECLARE
    result TIMESTAMP[];
    err_msg TEXT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        BEGIN
            result := (SELECT array_agg(occurrence ORDER BY occurrence)
                       FROM rrule."all"('FREQ=MINUTELY;BYDAY=2TU;COUNT=5', '2025-01-01 10:00:00'::TIMESTAMP) AS occurrence);
            RAISE EXCEPTION 'FAIL [reject-minutely-byday-ordinal]: RRULE was accepted when it should have been rejected';
        EXCEPTION
            WHEN raise_exception THEN
                err_msg := SQLERRM;
                IF err_msg LIKE '%BYDAY with ordinal%can only be used with FREQ=MONTHLY or FREQ=YEARLY%' THEN
                    RAISE NOTICE 'PASS [reject-minutely-byday-ordinal]';
                ELSE
                    RAISE EXCEPTION 'FAIL [reject-minutely-byday-ordinal]: Wrong error. Got: %', err_msg;
                END IF;
        END;
    ELSE
        RAISE NOTICE 'SKIP [reject-minutely-byday-ordinal]: Subday not installed';
    END IF;
END $$;

-- SECONDLY with BYDAY_ordinal should be rejected
DO $$
DECLARE
    result TIMESTAMP[];
    err_msg TEXT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        BEGIN
            result := (SELECT array_agg(occurrence ORDER BY occurrence)
                       FROM rrule."all"('FREQ=SECONDLY;BYDAY=2TU;COUNT=5', '2025-01-01 10:00:00'::TIMESTAMP) AS occurrence);
            RAISE EXCEPTION 'FAIL [reject-secondly-byday-ordinal]: RRULE was accepted when it should have been rejected';
        EXCEPTION
            WHEN raise_exception THEN
                err_msg := SQLERRM;
                IF err_msg LIKE '%BYDAY with ordinal%can only be used with FREQ=MONTHLY or FREQ=YEARLY%' THEN
                    RAISE NOTICE 'PASS [reject-secondly-byday-ordinal]';
                ELSE
                    RAISE EXCEPTION 'FAIL [reject-secondly-byday-ordinal]: Wrong error. Got: %', err_msg;
                END IF;
        END;
    ELSE
        RAISE NOTICE 'SKIP [reject-secondly-byday-ordinal]: Subday not installed';
    END IF;
END $$;

--------------------------------------------------------------------------------
-- FEATURE: BYMONTHDAY
--------------------------------------------------------------------------------
\echo ''
\echo '--- BYMONTHDAY ---'
\echo ''

-- DAILY with BYMONTHDAY=15
SELECT assert_true('matrix-daily-bymonthday',
    (SELECT COUNT(*) >= 1 FROM rrule."all"('FREQ=DAILY;BYMONTHDAY=15;COUNT=5', '2025-01-15 10:00:00'::TIMESTAMP)));

-- WEEKLY with BYMONTHDAY should be rejected
SELECT assert_rrule_rejected('reject-weekly-bymonthday',
    'FREQ=WEEKLY;BYMONTHDAY=15;COUNT=5',
    '%BYMONTHDAY cannot be used with FREQ=WEEKLY%');

-- MONTHLY with BYMONTHDAY=15
SELECT assert_true('matrix-monthly-bymonthday',
    (SELECT COUNT(*) >= 1 FROM rrule."all"('FREQ=MONTHLY;BYMONTHDAY=15;COUNT=5', '2025-01-15 10:00:00'::TIMESTAMP)));

-- YEARLY with BYMONTHDAY=15
SELECT assert_true('matrix-yearly-bymonthday',
    (SELECT COUNT(*) >= 1 FROM rrule."all"('FREQ=YEARLY;BYMONTHDAY=15;COUNT=5', '2025-01-15 10:00:00'::TIMESTAMP)));

-- HOURLY with BYMONTHDAY=15 (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=HOURLY;BYMONTHDAY=15;COUNT=5', '2025-01-15 10:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-hourly-bymonthday]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-hourly-bymonthday]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-hourly-bymonthday]: Subday not installed';
    END IF;
END $$;

-- MINUTELY with BYMONTHDAY=15 (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=MINUTELY;BYMONTHDAY=15;COUNT=5', '2025-01-15 10:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-minutely-bymonthday]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-minutely-bymonthday]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-minutely-bymonthday]: Subday not installed';
    END IF;
END $$;

-- SECONDLY with BYMONTHDAY=15 (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=SECONDLY;BYMONTHDAY=15;COUNT=5', '2025-01-15 10:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-secondly-bymonthday]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-secondly-bymonthday]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-secondly-bymonthday]: Subday not installed';
    END IF;
END $$;

--------------------------------------------------------------------------------
-- FEATURE: BYMONTHDAY_negative
--------------------------------------------------------------------------------
\echo ''
\echo '--- BYMONTHDAY_negative ---'
\echo ''

-- DAILY with BYMONTHDAY=-1 (last day)
SELECT assert_true('matrix-daily-bymonthday-negative',
    (SELECT COUNT(*) >= 1 FROM rrule."all"('FREQ=DAILY;BYMONTHDAY=-1;COUNT=5', '2025-01-31 10:00:00'::TIMESTAMP)));

-- WEEKLY with BYMONTHDAY_negative should be rejected
SELECT assert_rrule_rejected('reject-weekly-bymonthday-negative',
    'FREQ=WEEKLY;BYMONTHDAY=-1;COUNT=5',
    '%BYMONTHDAY cannot be used with FREQ=WEEKLY%');

-- MONTHLY with BYMONTHDAY=-1 (last day)
SELECT assert_true('matrix-monthly-bymonthday-negative',
    (SELECT COUNT(*) >= 1 FROM rrule."all"('FREQ=MONTHLY;BYMONTHDAY=-1;COUNT=5', '2025-01-31 10:00:00'::TIMESTAMP)));

-- YEARLY with BYMONTHDAY=-1 (last day)
SELECT assert_true('matrix-yearly-bymonthday-negative',
    (SELECT COUNT(*) >= 1 FROM rrule."all"('FREQ=YEARLY;BYMONTHDAY=-1;COUNT=5', '2025-01-31 10:00:00'::TIMESTAMP)));

-- HOURLY with BYMONTHDAY=-1 (last day) (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=HOURLY;BYMONTHDAY=-1;COUNT=5', '2025-01-31 10:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-hourly-bymonthday-negative]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-hourly-bymonthday-negative]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-hourly-bymonthday-negative]: Subday not installed';
    END IF;
END $$;

-- MINUTELY with BYMONTHDAY=-1 (last day) (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=MINUTELY;BYMONTHDAY=-1;COUNT=5', '2025-01-31 10:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-minutely-bymonthday-negative]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-minutely-bymonthday-negative]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-minutely-bymonthday-negative]: Subday not installed';
    END IF;
END $$;

-- SECONDLY with BYMONTHDAY=-1 (last day) (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=SECONDLY;BYMONTHDAY=-1;COUNT=5', '2025-01-31 10:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-secondly-bymonthday-negative]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-secondly-bymonthday-negative]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-secondly-bymonthday-negative]: Subday not installed';
    END IF;
END $$;

--------------------------------------------------------------------------------
-- FEATURE: BYMONTH
--------------------------------------------------------------------------------
\echo ''
\echo '--- BYMONTH ---'
\echo ''

-- DAILY with BYMONTH=1,6
SELECT assert_true('matrix-daily-bymonth',
    (SELECT COUNT(*) >= 1 FROM rrule."all"('FREQ=DAILY;BYMONTH=1,6;COUNT=10', '2025-01-01 10:00:00'::TIMESTAMP)));

-- WEEKLY with BYMONTH=1,6
SELECT assert_true('matrix-weekly-bymonth',
    (SELECT COUNT(*) >= 1 FROM rrule."all"('FREQ=WEEKLY;BYMONTH=1,6;COUNT=10', '2025-01-01 10:00:00'::TIMESTAMP)));

-- MONTHLY with BYMONTH=1,6
SELECT assert_true('matrix-monthly-bymonth',
    (SELECT COUNT(*) >= 1 FROM rrule."all"('FREQ=MONTHLY;BYMONTH=1,6;COUNT=10', '2025-01-01 10:00:00'::TIMESTAMP)));

-- YEARLY with BYMONTH=1,6
SELECT assert_true('matrix-yearly-bymonth',
    (SELECT COUNT(*) >= 1 FROM rrule."all"('FREQ=YEARLY;BYMONTH=1,6;COUNT=10', '2025-01-01 10:00:00'::TIMESTAMP)));

-- HOURLY with BYMONTH=1,6 (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=HOURLY;BYMONTH=1,6;COUNT=10', '2025-01-01 10:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-hourly-bymonth]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-hourly-bymonth]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-hourly-bymonth]: Subday not installed';
    END IF;
END $$;

-- MINUTELY with BYMONTH=1,6 (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=MINUTELY;BYMONTH=1,6;COUNT=10', '2025-01-01 10:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-minutely-bymonth]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-minutely-bymonth]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-minutely-bymonth]: Subday not installed';
    END IF;
END $$;

-- SECONDLY with BYMONTH=1,6 (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=SECONDLY;BYMONTH=1,6;COUNT=10', '2025-01-01 10:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-secondly-bymonth]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-secondly-bymonth]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-secondly-bymonth]: Subday not installed';
    END IF;
END $$;

--------------------------------------------------------------------------------
-- FEATURE: BYYEARDAY
--------------------------------------------------------------------------------
\echo ''
\echo '--- BYYEARDAY ---'
\echo ''

-- DAILY with BYYEARDAY should be rejected
SELECT assert_rrule_rejected('reject-daily-byyearday',
    'FREQ=DAILY;BYYEARDAY=100;COUNT=5',
    '%BYYEARDAY cannot be used with FREQ=%');

-- WEEKLY with BYYEARDAY should be rejected
SELECT assert_rrule_rejected('reject-weekly-byyearday',
    'FREQ=WEEKLY;BYYEARDAY=100;COUNT=5',
    '%BYYEARDAY cannot be used with FREQ=%');

-- MONTHLY with BYYEARDAY should be rejected
SELECT assert_rrule_rejected('reject-monthly-byyearday',
    'FREQ=MONTHLY;BYYEARDAY=100;COUNT=5',
    '%BYYEARDAY cannot be used with FREQ=%');

-- YEARLY with BYYEARDAY=100
SELECT assert_true('matrix-yearly-byyearday',
    (SELECT COUNT(*) >= 1 FROM rrule."all"('FREQ=YEARLY;BYYEARDAY=100;COUNT=5', '2025-01-01 10:00:00'::TIMESTAMP)));

-- HOURLY with BYYEARDAY=100 (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=HOURLY;BYYEARDAY=100;COUNT=5', '2025-04-10 00:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-hourly-byyearday]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-hourly-byyearday]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-hourly-byyearday]: Subday not installed';
    END IF;
END $$;

-- MINUTELY with BYYEARDAY=100 (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=MINUTELY;BYYEARDAY=100;COUNT=5', '2025-04-10 00:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-minutely-byyearday]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-minutely-byyearday]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-minutely-byyearday]: Subday not installed';
    END IF;
END $$;

-- SECONDLY with BYYEARDAY=100 (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=SECONDLY;BYYEARDAY=100;COUNT=5', '2025-04-10 00:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-secondly-byyearday]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-secondly-byyearday]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-secondly-byyearday]: Subday not installed';
    END IF;
END $$;

--------------------------------------------------------------------------------
-- FEATURE: BYYEARDAY_negative
--------------------------------------------------------------------------------
\echo ''
\echo '--- BYYEARDAY_negative ---'
\echo ''

-- DAILY with BYYEARDAY_negative should be rejected
SELECT assert_rrule_rejected('reject-daily-byyearday-negative',
    'FREQ=DAILY;BYYEARDAY=-1;COUNT=5',
    '%BYYEARDAY cannot be used with FREQ=%');

-- WEEKLY with BYYEARDAY_negative should be rejected
SELECT assert_rrule_rejected('reject-weekly-byyearday-negative',
    'FREQ=WEEKLY;BYYEARDAY=-1;COUNT=5',
    '%BYYEARDAY cannot be used with FREQ=%');

-- MONTHLY with BYYEARDAY_negative should be rejected
SELECT assert_rrule_rejected('reject-monthly-byyearday-negative',
    'FREQ=MONTHLY;BYYEARDAY=-1;COUNT=5',
    '%BYYEARDAY cannot be used with FREQ=%');

-- YEARLY with BYYEARDAY=-1 (last day of year)
SELECT assert_true('matrix-yearly-byyearday-negative',
    (SELECT COUNT(*) >= 1 FROM rrule."all"('FREQ=YEARLY;BYYEARDAY=-1;COUNT=5', '2025-12-31 10:00:00'::TIMESTAMP)));

-- HOURLY with BYYEARDAY=-1 (last day of year) (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=HOURLY;BYYEARDAY=-1;COUNT=5', '2025-12-31 10:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-hourly-byyearday-negative]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-hourly-byyearday-negative]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-hourly-byyearday-negative]: Subday not installed';
    END IF;
END $$;

-- MINUTELY with BYYEARDAY=-1 (last day of year) (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=MINUTELY;BYYEARDAY=-1;COUNT=5', '2025-12-31 10:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-minutely-byyearday-negative]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-minutely-byyearday-negative]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-minutely-byyearday-negative]: Subday not installed';
    END IF;
END $$;

-- SECONDLY with BYYEARDAY=-1 (last day of year) (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=SECONDLY;BYYEARDAY=-1;COUNT=5', '2025-12-31 10:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-secondly-byyearday-negative]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-secondly-byyearday-negative]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-secondly-byyearday-negative]: Subday not installed';
    END IF;
END $$;

--------------------------------------------------------------------------------
-- FEATURE: BYWEEKNO
--------------------------------------------------------------------------------
\echo ''
\echo '--- BYWEEKNO ---'
\echo ''

-- DAILY with BYWEEKNO should be rejected
SELECT assert_rrule_rejected('reject-daily-byweekno',
    'FREQ=DAILY;BYWEEKNO=10;COUNT=5',
    '%BYWEEKNO can only be used with FREQ=YEARLY%');

-- WEEKLY with BYWEEKNO should be rejected
SELECT assert_rrule_rejected('reject-weekly-byweekno',
    'FREQ=WEEKLY;BYWEEKNO=10;COUNT=5',
    '%BYWEEKNO can only be used with FREQ=YEARLY%');

-- MONTHLY with BYWEEKNO should be rejected
SELECT assert_rrule_rejected('reject-monthly-byweekno',
    'FREQ=MONTHLY;BYWEEKNO=10;COUNT=5',
    '%BYWEEKNO can only be used with FREQ=YEARLY%');

-- YEARLY with BYWEEKNO=10
SELECT assert_true('matrix-yearly-byweekno',
    (SELECT COUNT(*) >= 1 FROM rrule."all"('FREQ=YEARLY;BYWEEKNO=10;COUNT=5', '2025-01-01 10:00:00'::TIMESTAMP)));

-- HOURLY with BYWEEKNO should be rejected
DO $$
DECLARE
    result TIMESTAMP[];
    err_msg TEXT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        BEGIN
            result := (SELECT array_agg(occurrence ORDER BY occurrence)
                       FROM rrule."all"('FREQ=HOURLY;BYWEEKNO=10;COUNT=5', '2025-01-01 10:00:00'::TIMESTAMP) AS occurrence);
            RAISE EXCEPTION 'FAIL [reject-hourly-byweekno]: RRULE was accepted when it should have been rejected';
        EXCEPTION
            WHEN raise_exception THEN
                err_msg := SQLERRM;
                IF err_msg LIKE '%BYWEEKNO can only be used with FREQ=YEARLY%' THEN
                    RAISE NOTICE 'PASS [reject-hourly-byweekno]';
                ELSE
                    RAISE EXCEPTION 'FAIL [reject-hourly-byweekno]: Wrong error. Got: %', err_msg;
                END IF;
        END;
    ELSE
        RAISE NOTICE 'SKIP [reject-hourly-byweekno]: Subday not installed';
    END IF;
END $$;

-- MINUTELY with BYWEEKNO should be rejected
DO $$
DECLARE
    result TIMESTAMP[];
    err_msg TEXT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        BEGIN
            result := (SELECT array_agg(occurrence ORDER BY occurrence)
                       FROM rrule."all"('FREQ=MINUTELY;BYWEEKNO=10;COUNT=5', '2025-01-01 10:00:00'::TIMESTAMP) AS occurrence);
            RAISE EXCEPTION 'FAIL [reject-minutely-byweekno]: RRULE was accepted when it should have been rejected';
        EXCEPTION
            WHEN raise_exception THEN
                err_msg := SQLERRM;
                IF err_msg LIKE '%BYWEEKNO can only be used with FREQ=YEARLY%' THEN
                    RAISE NOTICE 'PASS [reject-minutely-byweekno]';
                ELSE
                    RAISE EXCEPTION 'FAIL [reject-minutely-byweekno]: Wrong error. Got: %', err_msg;
                END IF;
        END;
    ELSE
        RAISE NOTICE 'SKIP [reject-minutely-byweekno]: Subday not installed';
    END IF;
END $$;

-- SECONDLY with BYWEEKNO should be rejected
DO $$
DECLARE
    result TIMESTAMP[];
    err_msg TEXT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        BEGIN
            result := (SELECT array_agg(occurrence ORDER BY occurrence)
                       FROM rrule."all"('FREQ=SECONDLY;BYWEEKNO=10;COUNT=5', '2025-01-01 10:00:00'::TIMESTAMP) AS occurrence);
            RAISE EXCEPTION 'FAIL [reject-secondly-byweekno]: RRULE was accepted when it should have been rejected';
        EXCEPTION
            WHEN raise_exception THEN
                err_msg := SQLERRM;
                IF err_msg LIKE '%BYWEEKNO can only be used with FREQ=YEARLY%' THEN
                    RAISE NOTICE 'PASS [reject-secondly-byweekno]';
                ELSE
                    RAISE EXCEPTION 'FAIL [reject-secondly-byweekno]: Wrong error. Got: %', err_msg;
                END IF;
        END;
    ELSE
        RAISE NOTICE 'SKIP [reject-secondly-byweekno]: Subday not installed';
    END IF;
END $$;

--------------------------------------------------------------------------------
-- FEATURE: WKST
--------------------------------------------------------------------------------
\echo ''
\echo '--- WKST ---'
\echo ''

-- DAILY with WKST=SU
SELECT assert_equals('matrix-daily-wkst', '5',
    (SELECT COUNT(*)::TEXT FROM rrule."all"('FREQ=DAILY;WKST=SU;COUNT=5', '2025-01-01 10:00:00'::TIMESTAMP)));

-- WEEKLY with WKST=SU
SELECT assert_equals('matrix-weekly-wkst', '5',
    (SELECT COUNT(*)::TEXT FROM rrule."all"('FREQ=WEEKLY;WKST=SU;COUNT=5', '2025-01-01 10:00:00'::TIMESTAMP)));

-- MONTHLY with WKST=SU
SELECT assert_equals('matrix-monthly-wkst', '5',
    (SELECT COUNT(*)::TEXT FROM rrule."all"('FREQ=MONTHLY;WKST=SU;COUNT=5', '2025-01-01 10:00:00'::TIMESTAMP)));

-- YEARLY with WKST=SU
SELECT assert_equals('matrix-yearly-wkst', '5',
    (SELECT COUNT(*)::TEXT FROM rrule."all"('FREQ=YEARLY;WKST=SU;COUNT=5', '2025-01-01 10:00:00'::TIMESTAMP)));

-- HOURLY with WKST=SU (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=HOURLY;WKST=SU;COUNT=5', '2025-01-01 10:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-hourly-wkst]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-hourly-wkst]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-hourly-wkst]: Subday not installed';
    END IF;
END $$;

-- MINUTELY with WKST=SU (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=MINUTELY;WKST=SU;COUNT=5', '2025-01-01 10:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-minutely-wkst]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-minutely-wkst]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-minutely-wkst]: Subday not installed';
    END IF;
END $$;

-- SECONDLY with WKST=SU (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=SECONDLY;WKST=SU;COUNT=5', '2025-01-01 10:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-secondly-wkst]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-secondly-wkst]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-secondly-wkst]: Subday not installed';
    END IF;
END $$;

--------------------------------------------------------------------------------
-- FEATURE: BYHOUR
--------------------------------------------------------------------------------
\echo ''
\echo '--- BYHOUR ---'
\echo ''

-- DAILY with BYHOUR=9,12,17
SELECT assert_true('matrix-daily-byhour',
    (SELECT COUNT(*) >= 1 FROM rrule."all"('FREQ=DAILY;BYHOUR=9,12,17;COUNT=15', '2025-01-01 09:00:00'::TIMESTAMP)));

-- WEEKLY with BYHOUR should be rejected
SELECT assert_rrule_rejected('reject-weekly-byhour',
    'FREQ=WEEKLY;BYHOUR=9,12,17;COUNT=15',
    '%BYHOUR%not supported with FREQ=%');

-- MONTHLY with BYHOUR should be rejected
SELECT assert_rrule_rejected('reject-monthly-byhour',
    'FREQ=MONTHLY;BYHOUR=9,12,17;COUNT=15',
    '%BYHOUR%not supported with FREQ=%');

-- YEARLY with BYHOUR should be rejected
SELECT assert_rrule_rejected('reject-yearly-byhour',
    'FREQ=YEARLY;BYHOUR=9,12,17;COUNT=15',
    '%BYHOUR%not supported with FREQ=%');

-- HOURLY with BYHOUR=9,12,17 (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=HOURLY;BYHOUR=9,12,17;COUNT=15', '2025-01-01 09:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-hourly-byhour]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-hourly-byhour]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-hourly-byhour]: Subday not installed';
    END IF;
END $$;

-- MINUTELY with BYHOUR=9,12,17 (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=MINUTELY;BYHOUR=9,12,17;COUNT=15', '2025-01-01 09:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-minutely-byhour]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-minutely-byhour]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-minutely-byhour]: Subday not installed';
    END IF;
END $$;

-- SECONDLY with BYHOUR=9,12,17 (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=SECONDLY;BYHOUR=9,12,17;COUNT=15', '2025-01-01 09:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-secondly-byhour]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-secondly-byhour]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-secondly-byhour]: Subday not installed';
    END IF;
END $$;

--------------------------------------------------------------------------------
-- FEATURE: BYMINUTE
--------------------------------------------------------------------------------
\echo ''
\echo '--- BYMINUTE ---'
\echo ''

-- DAILY with BYMINUTE=0,30
SELECT assert_true('matrix-daily-byminute',
    (SELECT COUNT(*) >= 1 FROM rrule."all"('FREQ=DAILY;BYMINUTE=0,30;COUNT=10', '2025-01-01 10:00:00'::TIMESTAMP)));

-- WEEKLY with BYMINUTE should be rejected
SELECT assert_rrule_rejected('reject-weekly-byminute',
    'FREQ=WEEKLY;BYMINUTE=0,30;COUNT=10',
    '%BYMINUTE%not supported with FREQ=%');

-- MONTHLY with BYMINUTE should be rejected
SELECT assert_rrule_rejected('reject-monthly-byminute',
    'FREQ=MONTHLY;BYMINUTE=0,30;COUNT=10',
    '%BYMINUTE%not supported with FREQ=%');

-- YEARLY with BYMINUTE should be rejected
SELECT assert_rrule_rejected('reject-yearly-byminute',
    'FREQ=YEARLY;BYMINUTE=0,30;COUNT=10',
    '%BYMINUTE%not supported with FREQ=%');

-- HOURLY with BYMINUTE=0,30 (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=HOURLY;BYMINUTE=0,30;COUNT=10', '2025-01-01 10:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-hourly-byminute]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-hourly-byminute]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-hourly-byminute]: Subday not installed';
    END IF;
END $$;

-- MINUTELY with BYMINUTE=0,30 (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=MINUTELY;BYMINUTE=0,30;COUNT=10', '2025-01-01 10:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-minutely-byminute]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-minutely-byminute]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-minutely-byminute]: Subday not installed';
    END IF;
END $$;

-- SECONDLY with BYMINUTE=0,30 (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=SECONDLY;BYMINUTE=0,30;COUNT=10', '2025-01-01 10:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-secondly-byminute]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-secondly-byminute]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-secondly-byminute]: Subday not installed';
    END IF;
END $$;

--------------------------------------------------------------------------------
-- FEATURE: BYSECOND
--------------------------------------------------------------------------------
\echo ''
\echo '--- BYSECOND ---'
\echo ''

-- DAILY with BYSECOND=0,30
SELECT assert_true('matrix-daily-bysecond',
    (SELECT COUNT(*) >= 1 FROM rrule."all"('FREQ=DAILY;BYSECOND=0,30;COUNT=10', '2025-01-01 10:00:00'::TIMESTAMP)));

-- WEEKLY with BYSECOND should be rejected
SELECT assert_rrule_rejected('reject-weekly-bysecond',
    'FREQ=WEEKLY;BYSECOND=0,30;COUNT=10',
    '%BYSECOND%not supported with FREQ=%');

-- MONTHLY with BYSECOND should be rejected
SELECT assert_rrule_rejected('reject-monthly-bysecond',
    'FREQ=MONTHLY;BYSECOND=0,30;COUNT=10',
    '%BYSECOND%not supported with FREQ=%');

-- YEARLY with BYSECOND should be rejected
SELECT assert_rrule_rejected('reject-yearly-bysecond',
    'FREQ=YEARLY;BYSECOND=0,30;COUNT=10',
    '%BYSECOND%not supported with FREQ=%');

-- HOURLY with BYSECOND=0,30 (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=HOURLY;BYSECOND=0,30;COUNT=10', '2025-01-01 10:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-hourly-bysecond]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-hourly-bysecond]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-hourly-bysecond]: Subday not installed';
    END IF;
END $$;

-- MINUTELY with BYSECOND=0,30 (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=MINUTELY;BYSECOND=0,30;COUNT=10', '2025-01-01 10:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-minutely-bysecond]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-minutely-bysecond]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-minutely-bysecond]: Subday not installed';
    END IF;
END $$;

-- SECONDLY with BYSECOND=0,30 (subday-only)
DO $$
DECLARE
    result TEXT;
    cnt INT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        SELECT COUNT(*) INTO cnt FROM rrule."all"('FREQ=SECONDLY;BYSECOND=0,30;COUNT=10', '2025-01-01 10:00:00'::TIMESTAMP);
        IF cnt >= 1 THEN
            RAISE NOTICE 'PASS [matrix-secondly-bysecond]';
        ELSE
            RAISE EXCEPTION 'FAIL [matrix-secondly-bysecond]: Expected at least 1 results, got %', cnt;
        END IF;
    ELSE
        RAISE NOTICE 'SKIP [matrix-secondly-bysecond]: Subday not installed';
    END IF;
END $$;

--------------------------------------------------------------------------------
-- FEATURE: BYSETPOS
--------------------------------------------------------------------------------
\echo ''
\echo '--- BYSETPOS ---'
\echo ''

-- DAILY with BYSETPOS=1,-1
SELECT assert_true('matrix-daily-bysetpos',
    (SELECT COUNT(*) >= 1 FROM rrule."all"('FREQ=DAILY;BYDAY=MO,TU,WE,TH,FR;BYSETPOS=1,-1;COUNT=10', '2025-01-01 10:00:00'::TIMESTAMP)));

-- WEEKLY with BYSETPOS=1,-1
SELECT assert_true('matrix-weekly-bysetpos',
    (SELECT COUNT(*) >= 1 FROM rrule."all"('FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR;BYSETPOS=1,-1;COUNT=10', '2025-01-01 10:00:00'::TIMESTAMP)));

-- MONTHLY with BYSETPOS=1,-1
SELECT assert_true('matrix-monthly-bysetpos',
    (SELECT COUNT(*) >= 1 FROM rrule."all"('FREQ=MONTHLY;BYDAY=MO,TU,WE,TH,FR;BYSETPOS=1,-1;COUNT=10', '2025-01-01 10:00:00'::TIMESTAMP)));

-- YEARLY with BYSETPOS=1,-1
SELECT assert_true('matrix-yearly-bysetpos',
    (SELECT COUNT(*) >= 1 FROM rrule."all"('FREQ=YEARLY;BYMONTH=1;BYDAY=MO,TU,WE,TH,FR;BYSETPOS=1,-1;COUNT=10', '2025-01-01 10:00:00'::TIMESTAMP)));

-- HOURLY with BYSETPOS should be rejected
DO $$
DECLARE
    result TIMESTAMP[];
    err_msg TEXT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        BEGIN
            result := (SELECT array_agg(occurrence ORDER BY occurrence)
                       FROM rrule."all"('FREQ=HOURLY;BYDAY=MO,TU,WE,TH,FR;BYSETPOS=1,-1;COUNT=10', '2025-01-01 10:00:00'::TIMESTAMP) AS occurrence);
            RAISE EXCEPTION 'FAIL [reject-hourly-bysetpos]: RRULE was accepted when it should have been rejected';
        EXCEPTION
            WHEN raise_exception THEN
                err_msg := SQLERRM;
                IF err_msg LIKE '%BYSETPOS%not supported%' THEN
                    RAISE NOTICE 'PASS [reject-hourly-bysetpos]';
                ELSE
                    RAISE EXCEPTION 'FAIL [reject-hourly-bysetpos]: Wrong error. Got: %', err_msg;
                END IF;
        END;
    ELSE
        RAISE NOTICE 'SKIP [reject-hourly-bysetpos]: Subday not installed';
    END IF;
END $$;

-- MINUTELY with BYSETPOS should be rejected
DO $$
DECLARE
    result TIMESTAMP[];
    err_msg TEXT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        BEGIN
            result := (SELECT array_agg(occurrence ORDER BY occurrence)
                       FROM rrule."all"('FREQ=MINUTELY;BYDAY=MO,TU,WE,TH,FR;BYSETPOS=1,-1;COUNT=10', '2025-01-01 10:00:00'::TIMESTAMP) AS occurrence);
            RAISE EXCEPTION 'FAIL [reject-minutely-bysetpos]: RRULE was accepted when it should have been rejected';
        EXCEPTION
            WHEN raise_exception THEN
                err_msg := SQLERRM;
                IF err_msg LIKE '%BYSETPOS%not supported%' THEN
                    RAISE NOTICE 'PASS [reject-minutely-bysetpos]';
                ELSE
                    RAISE EXCEPTION 'FAIL [reject-minutely-bysetpos]: Wrong error. Got: %', err_msg;
                END IF;
        END;
    ELSE
        RAISE NOTICE 'SKIP [reject-minutely-bysetpos]: Subday not installed';
    END IF;
END $$;

-- SECONDLY with BYSETPOS should be rejected
DO $$
DECLARE
    result TIMESTAMP[];
    err_msg TEXT;
BEGIN
    IF (SELECT subday_installed FROM test_config) THEN
        BEGIN
            result := (SELECT array_agg(occurrence ORDER BY occurrence)
                       FROM rrule."all"('FREQ=SECONDLY;BYDAY=MO,TU,WE,TH,FR;BYSETPOS=1,-1;COUNT=10', '2025-01-01 10:00:00'::TIMESTAMP) AS occurrence);
            RAISE EXCEPTION 'FAIL [reject-secondly-bysetpos]: RRULE was accepted when it should have been rejected';
        EXCEPTION
            WHEN raise_exception THEN
                err_msg := SQLERRM;
                IF err_msg LIKE '%BYSETPOS%not supported%' THEN
                    RAISE NOTICE 'PASS [reject-secondly-bysetpos]';
                ELSE
                    RAISE EXCEPTION 'FAIL [reject-secondly-bysetpos]: Wrong error. Got: %', err_msg;
                END IF;
        END;
    ELSE
        RAISE NOTICE 'SKIP [reject-secondly-bysetpos]: Subday not installed';
    END IF;
END $$;


\echo ''
\echo '====================================================================='
\echo 'AUTO-GENERATED SPEC COMPLIANCE MATRIX TESTS COMPLETE'
\echo '====================================================================='

ROLLBACK;

